# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: firetaskgroup
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fire-task-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fire-task

provider:
  name: aws
  runtime: python3.13
  iam:
    role: ${env:LAB_ROLE_ARN}

package:
  patterns:
    - '!**'
    - 'handler.py'
    - 'features/**'
    - 'requirements.txt'

functions:
  recognizer:
    handler: handler.lambda_handler
    role: ${env:LAB_ROLE_ARN}
    layers:
      - Ref: PythonRequirementsLambdaLayer
    # labrole doesn't have permissions to create roles which serverless uses when attaching handler to bucket
    # as such configuration to attach to bucket will need to be done manually

custom:
  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
